# .rubocop.yml
AllCops:
  Exclude:
    - 'vendor/**/*'
    - '.bundle/**/*'
    - 'vendor/bundle/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false