# .rubocop.yml
AllCops:
  Exclude:
    - 'vendor/**/*'
    - '.bundle/**/*'
    - 'vendor/bundle/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'bin/*'
    - 'exe/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false