name: Ruby

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.1'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Remove frozen Gemfile.lock mode
        run: bundle config set frozen false
      - name: Install all the gems
        run: bundle install --jobs 4 --retry 3
      - name: Run the test
        run: bundle exec rspec
